# Generated by Django 5.1.3 on 2025-01-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cardsQuantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(default='Album', max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='total_price',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='konami_id',
            field=models.CharField(default='00000000', max_length=8),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='real_image',
            field=models.ImageField(blank=True, null=True, upload_to='example/'),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='stock',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
