# Generated by Django 5.1.3 on 2025-01-08 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_albumcard_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_name', models.CharField(max_length=255)),
                ('set_code', models.CharField(max_length=255)),
                ('set_rarity', models.CharField(max_length=255)),
                ('set_rarity_code', models.CharField(max_length=255)),
                ('set_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konami_id', models.CharField(default='0', max_length=8)),
                ('name', models.CharField(max_length=255)),
                ('typeline', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(max_length=255)),
                ('humanReadableCardType', models.CharField(max_length=255)),
                ('frameType', models.CharField(max_length=255)),
                ('desc', models.TextField()),
                ('race', models.CharField(max_length=255)),
                ('pend_desc', models.TextField(blank=True, null=True)),
                ('monster_desc', models.TextField(blank=True, null=True)),
                ('atk', models.IntegerField(blank=True, null=True)),
                ('defense', models.IntegerField(blank=True, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('attribute', models.CharField(blank=True, max_length=255, null=True)),
                ('archetype', models.CharField(blank=True, max_length=255, null=True)),
                ('scale', models.IntegerField(blank=True, null=True)),
                ('linkval', models.IntegerField(blank=True, null=True)),
                ('linkmarkers', models.JSONField(blank=True, null=True)),
                ('ygoprodeck_url', models.URLField()),
                ('album_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='card.albumcard')),
                ('card_sets', models.ManyToManyField(related_name='cards', to='card.cardset')),
            ],
        ),
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('image_url_small', models.URLField()),
                ('image_url_cropped', models.URLField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='card.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardmarket_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tcgplayer_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ebay_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amazon_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coolstuffinc_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_prices', to='card.card')),
            ],
        ),
    ]
