# Generated by Django 5.1.4 on 2025-01-09 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_cardset_card_cardimage_cardprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='album_card',
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_sets',
        ),
        migrations.RemoveField(
            model_name='cardprice',
            name='card',
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='card',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_images', to='card.albumcard'),
        ),
        migrations.RemoveField(
            model_name='albumcard',
            name='real_image',
        ),
        migrations.AddField(
            model_name='albumcard',
            name='archetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='atk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='attribute',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='defense',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='frameType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='humanReadableCardType',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='linkmarkers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='linkval',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='monster_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='name',
            field=models.CharField(default=11, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='pend_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='race',
            field=models.CharField(default=11111, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='rarity',
            field=models.CharField(choices=[('1', 'Comun'), ('2', 'Rare'), ('3', 'Super rare'), ('4', 'Ultra rare'), ('5', 'Secret rare')], default='l', max_length=1),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='scale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='albumcard',
            name='type',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumcard',
            name='typeline',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albumcard',
            name='konami_id',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.DeleteModel(
            name='CardSet',
        ),
        migrations.DeleteModel(
            name='CardPrice',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
