# Generated by Django 5.1.4 on 2025-01-09 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_remove_card_album_card_remove_card_card_sets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumcard',
            name='version',
            field=models.CharField(choices=[('1', 'Comun'), ('2', 'Rare'), ('3', 'Super rare'), ('4', 'Ultra rare'), ('5', 'Secret rare')], default='l', max_length=1),
        ),
        migrations.AlterField(
            model_name='albumcard',
            name='rarity',
            field=models.CharField(choices=[('1', 'TCG'), ('2', 'OCG')], default='l', max_length=1),
        ),
    ]
