# Generated by Django 5.1.3 on 2025-01-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0007_albumcard_version_alter_albumcard_rarity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcard',
            name='rarity',
            field=models.CharField(choices=[('1', 'Comun'), ('2', 'Rare'), ('3', 'Super rare'), ('4', 'Ultra rare'), ('5', 'Secret rare')], default='l', max_length=1),
        ),
        migrations.AlterField(
            model_name='albumcard',
            name='version',
            field=models.CharField(choices=[('1', 'TCG'), ('2', 'OCG')], default='l', max_length=1),
        ),
    ]
