# Generated by Django 5.1.4 on 2025-01-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0010_albumcard_expantion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumcard',
            name='attribute',
            field=models.CharField(blank=True, choices=[('1', 'FIRE'), ('2', 'WATER'), ('3', 'WIND'), ('4', 'EARTH'), ('5', 'DARK'), ('6', 'LIGHT'), ('7', 'DIVINE')], max_length=1, null=True),
        ),
    ]
