# Generated by Django 5.1.4 on 2025-01-27 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0011_alter_albumcard_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumcard',
            old_name='type',
            new_name='tipo',
        ),
    ]
