# Generated by Django 5.1.4 on 2025-02-04 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0015_alter_albumdecks_options_alter_albumdecks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdecks',
            name='image',
            field=models.ImageField(null=True, upload_to='AlbumDeck'),
        ),
    ]
