# Generated by Django 5.1.4 on 2025-03-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0020_alter_albumdecks_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumdecks',
            name='stock',
            field=models.IntegerField(default=1),
        ),
    ]
