# Generated by Django 5.1.4 on 2025-01-13 01:00

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('month_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='FeatureSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_subscription', to='general.subscription', verbose_name='feature_subscription')),
            ],
            options={
                'verbose_name': 'Feature of Subscription',
                'verbose_name_plural': 'Features of Subscription',
            },
        ),
    ]
