# Generated by Django 5.1.4 on 2025-01-13 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_featuresubscription_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='price',
            new_name='annual_price',
        ),
    ]
