# Generated by Django 5.1.4 on 2025-01-13 01:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_remove_subscription_annual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='annual_price_discount',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
