# Generated by Django 5.1.4 on 2025-01-13 01:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_coin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='CUP',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
