# Generated by Django 5.1.4 on 2025-01-13 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_coin_cup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coin',
            old_name='CUP',
            new_name='cup',
        ),
    ]
