# Generated by Django 5.1.4 on 2025-01-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_subscription_description_alter_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='popular',
            field=models.BooleanField(default=False),
        ),
    ]
