# Generated by Django 5.1.4 on 2025-01-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='delivery_date_time',
        ),
        migrations.AddField(
            model_name='item',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
