# Generated by Django 5.1.4 on 2025-01-13 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_item_delivery_item_state_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.order'),
        ),
    ]
