# Generated by Django 5.1.4 on 2025-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_remove_order_current_user_order_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'Carta'), ('2', 'Deck'), ('3', 'Playmat'), ('4', 'Forro')], default='1', max_length=1),
        ),
    ]
