# Generated by Django 5.1.4 on 2025-02-26 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('1', 'Carta'), ('2', 'Deck')], default='1', max_length=1),
        ),
    ]
